#!/bin/bash
################################################################################
# ARIA Production Deployment - Quick Commands
# 
# Run these commands to deploy ARIA to your production server
################################################################################

echo "ARIA Production Deployment Commands"
echo "===================================="
echo ""
echo "Step 1: Make PEM file secure"
echo "----------------------------"
echo "chmod 400 /workspace/project/VantaX-2.pem"
echo ""
echo "Step 2: Create deployment package"
echo "----------------------------------"
echo "cd /workspace/project"
echo "tar -czf aria-deployment.tar.gz Aria---Document-Management-Employee/"
echo ""
echo "Step 3: Transfer to production server"
echo "--------------------------------------"
echo "scp -i /workspace/project/VantaX-2.pem aria-deployment.tar.gz ubuntu@3.8.139.178:/home/ubuntu/"
echo "scp -i /workspace/project/VantaX-2.pem Aria---Document-Management-Employee/deploy_production.sh ubuntu@3.8.139.178:/home/ubuntu/"
echo "scp -i /workspace/project/VantaX-2.pem Aria---Document-Management-Employee/test_production.py ubuntu@3.8.139.178:/home/ubuntu/"
echo ""
echo "Step 4: SSH into server and deploy"
echo "-----------------------------------"
echo "ssh -i /workspace/project/VantaX-2.pem ubuntu@3.8.139.178"
echo ""
echo "# Once connected, run these commands:"
echo "tar -xzf aria-deployment.tar.gz"
echo "cd Aria---Document-Management-Employee"
echo "chmod +x deploy_production.sh"
echo "./deploy_production.sh"
echo ""
echo "Step 5: Run end-to-end tests"
echo "----------------------------"
echo "python3 test_production.py --server 3.8.139.178"
echo ""
echo "Step 6: Access your application"
echo "--------------------------------"
echo "Frontend:  http://3.8.139.178:3000"
echo "Backend:   http://3.8.139.178:8000/api/v1"
echo "API Docs:  http://3.8.139.178:8000/api/v1/docs"
echo ""
