"""
Bot Data Access Layer - PostgreSQL
Provides company-scoped helper functions for bots to access real ERP data
All functions require company_id for multi-tenancy security
"""

import psycopg2
import psycopg2.extras
import os
from typing import Dict, Any, List, Optional
from datetime import datetime, timedelta
import uuid

DATABASE_URL = os.getenv("DATABASE_URL_PG") or os.getenv("DATABASE_URL")

def get_connection():
    """Get PostgreSQL database connection"""
    if not DATABASE_URL:
        raise RuntimeError("DATABASE_URL_PG or DATABASE_URL environment variable must be set")
    return psycopg2.connect(DATABASE_URL)

# ========================================
# ========================================

def fetch_outstanding_ar_invoices(company_id: str, limit: int = 100) -> List[Dict[str, Any]]:
    """Fetch outstanding AR invoices for a company"""
    conn = get_connection()
    cursor = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        cursor.execute("""
            SELECT ci.*, c.customer_name,
                   CASE 
                       WHEN ci.due_date < CURRENT_DATE THEN CURRENT_DATE - ci.due_date
                       ELSE 0
                   END as days_overdue
            FROM customer_invoices ci
            LEFT JOIN customers c ON ci.customer_id = c.id
            WHERE ci.company_id = %s 
              AND ci.status IN ('open', 'overdue')
            ORDER BY ci.due_date ASC
            LIMIT %s
        """, (company_id, limit))
        return cursor.fetchall()
    finally:
        cursor.close()
        conn.close()

def fetch_ap_bills_due(company_id: str, days_ahead: int = 30, limit: int = 100) -> List[Dict[str, Any]]:
    """Fetch AP bills due within specified days"""
    conn = get_connection()
    cursor = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        cursor.execute("""
            SELECT si.*, s.supplier_name
            FROM supplier_invoices si
            LEFT JOIN suppliers s ON si.supplier_id = s.id
            WHERE si.company_id = %s 
              AND si.status IN ('pending', 'approved')
              AND si.due_date <= CURRENT_DATE + INTERVAL '%s days'
            ORDER BY si.due_date ASC
            LIMIT %s
        """, (company_id, days_ahead, limit))
        return cursor.fetchall()
    finally:
        cursor.close()
        conn.close()

def fetch_bank_transactions(company_id: str, account_id: Optional[str] = None, 
                            days_back: int = 30, limit: int = 100) -> List[Dict[str, Any]]:
    """Fetch bank transactions for reconciliation"""
    conn = get_connection()
    cursor = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        query = """
            SELECT bt.*, ba.account_name, ba.account_number
            FROM bank_transactions bt
            LEFT JOIN bank_accounts ba ON bt.bank_account_id = ba.id
            WHERE bt.company_id = %s 
              AND bt.transaction_date >= CURRENT_DATE - INTERVAL '%s days'
        """
        params = [company_id, days_back]
        
        if account_id:
            query += " AND bt.bank_account_id = %s"
            params.append(account_id)
        
        query += " ORDER BY bt.transaction_date DESC LIMIT %s"
        params.append(limit)
        
        cursor.execute(query, params)
        return cursor.fetchall()
    finally:
        cursor.close()
        conn.close()

def create_journal_entry(company_id: str, entry_data: Dict[str, Any], dry_run: bool = True) -> Dict[str, Any]:
    """Create a journal entry (dry_run by default)"""
    if dry_run:
        return {
            "dry_run": True,
            "message": "Journal entry validated but not created",
            "entry_data": entry_data
        }
    
    conn = get_connection()
    cursor = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        cursor.execute("SELECT COALESCE(MAX(CAST(SUBSTRING(entry_number FROM 'JE-([0-9]+)') AS INTEGER)), 0) + 1 as next_num FROM journal_entries WHERE company_id = %s", (company_id,))
        next_num = cursor.fetchone()['next_num']
        entry_number = f"JE-{next_num:05d}"
        
        entry_id = str(uuid.uuid4())
        cursor.execute("""
            INSERT INTO journal_entries (id, company_id, entry_number, entry_date, description, status, created_at, updated_at)
            VALUES (%s, %s, %s, %s, %s, 'draft', NOW(), NOW())
            RETURNING id, entry_number
        """, (entry_id, company_id, entry_number, entry_data.get('entry_date', datetime.now().date()),
              entry_data.get('description', 'Auto-generated by bot')))
        
        result = cursor.fetchone()
        
        for line in entry_data.get('lines', []):
            cursor.execute("""
                INSERT INTO journal_entry_lines (id, journal_entry_id, account_id, debit, credit, description, created_at, updated_at)
                VALUES (%s, %s, %s, %s, %s, %s, NOW(), NOW())
            """, (str(uuid.uuid4()), entry_id, line.get('account_id'), 
                  line.get('debit', 0), line.get('credit', 0), line.get('description', '')))
        
        conn.commit()
        return {'id': str(result['id']), 'entry_number': result['entry_number'], 'dry_run': False}
    except Exception as e:
        conn.rollback()
        raise e
    finally:
        cursor.close()
        conn.close()

def fetch_chart_of_accounts(company_id: str) -> List[Dict[str, Any]]:
    """Fetch chart of accounts for a company"""
    conn = get_connection()
    cursor = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        cursor.execute("""
            SELECT * FROM chart_of_accounts
            WHERE company_id = %s
            ORDER BY account_code
        """, (company_id,))
        return cursor.fetchall()
    finally:
        cursor.close()
        conn.close()

def fetch_payroll_runs(company_id: str, limit: int = 10) -> List[Dict[str, Any]]:
    """Fetch recent payroll runs"""
    conn = get_connection()
    cursor = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        cursor.execute("""
            SELECT * FROM payroll_runs
            WHERE company_id = %s
            ORDER BY pay_period_end DESC
            LIMIT %s
        """, (company_id, limit))
        return cursor.fetchall()
    finally:
        cursor.close()
        conn.close()

# ========================================
# ========================================

def fetch_open_purchase_orders(company_id: str, limit: int = 100) -> List[Dict[str, Any]]:
    """Fetch open purchase orders"""
    conn = get_connection()
    cursor = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        cursor.execute("""
            SELECT po.*, s.supplier_name
            FROM purchase_orders po
            LEFT JOIN suppliers s ON po.supplier_id = s.id
            WHERE po.company_id = %s 
              AND po.status IN ('draft', 'approved', 'sent')
            ORDER BY po.order_date DESC
            LIMIT %s
        """, (company_id, limit))
        return cursor.fetchall()
    finally:
        cursor.close()
        conn.close()

def fetch_goods_receipts(company_id: str, limit: int = 100) -> List[Dict[str, Any]]:
    """Fetch recent goods receipts"""
    conn = get_connection()
    cursor = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        cursor.execute("""
            SELECT gr.*, po.po_number
            FROM goods_receipts gr
            LEFT JOIN purchase_orders po ON gr.purchase_order_id = po.id
            WHERE gr.company_id = %s
            ORDER BY gr.receipt_date DESC
            LIMIT %s
        """, (company_id, limit))
        return cursor.fetchall()
    finally:
        cursor.close()
        conn.close()

def fetch_suppliers(company_id: str, limit: int = 100) -> List[Dict[str, Any]]:
    """Fetch suppliers"""
    conn = get_connection()
    cursor = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        cursor.execute("""
            SELECT * FROM suppliers
            WHERE company_id = %s
            ORDER BY supplier_name
            LIMIT %s
        """, (company_id, limit))
        return cursor.fetchall()
    finally:
        cursor.close()
        conn.close()

# ========================================
# ========================================

def fetch_work_orders(company_id: str, status: Optional[str] = None, limit: int = 100) -> List[Dict[str, Any]]:
    """Fetch work orders"""
    conn = get_connection()
    cursor = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        query = """
            SELECT wo.*, p.product_name
            FROM work_orders wo
            LEFT JOIN products p ON wo.product_id = p.id
            WHERE wo.company_id = %s
        """
        params = [company_id]
        
        if status:
            query += " AND wo.status = %s"
            params.append(status)
        
        query += " ORDER BY wo.start_date DESC LIMIT %s"
        params.append(limit)
        
        cursor.execute(query, params)
        return cursor.fetchall()
    finally:
        cursor.close()
        conn.close()

def fetch_boms(company_id: str, limit: int = 100) -> List[Dict[str, Any]]:
    """Fetch bills of materials"""
    conn = get_connection()
    cursor = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        cursor.execute("""
            SELECT b.*, p.product_name
            FROM boms b
            LEFT JOIN products p ON b.product_id = p.id
            WHERE b.company_id = %s
            ORDER BY b.created_at DESC
            LIMIT %s
        """, (company_id, limit))
        return cursor.fetchall()
    finally:
        cursor.close()
        conn.close()

def fetch_production_runs(company_id: str, limit: int = 100) -> List[Dict[str, Any]]:
    """Fetch production runs"""
    conn = get_connection()
    cursor = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        cursor.execute("""
            SELECT pr.*, wo.work_order_number
            FROM production_runs pr
            LEFT JOIN work_orders wo ON pr.work_order_id = wo.id
            WHERE pr.company_id = %s
            ORDER BY pr.start_date DESC
            LIMIT %s
        """, (company_id, limit))
        return cursor.fetchall()
    finally:
        cursor.close()
        conn.close()

# ========================================
# ========================================

def fetch_leads(company_id: str, status: Optional[str] = None, limit: int = 100) -> List[Dict[str, Any]]:
    """Fetch leads"""
    conn = get_connection()
    cursor = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        query = "SELECT * FROM leads WHERE company_id = %s"
        params = [company_id]
        
        if status:
            query += " AND status = %s"
            params.append(status)
        
        query += " ORDER BY created_at DESC LIMIT %s"
        params.append(limit)
        
        cursor.execute(query, params)
        return cursor.fetchall()
    finally:
        cursor.close()
        conn.close()

def fetch_opportunities(company_id: str, status: Optional[str] = None, limit: int = 100) -> List[Dict[str, Any]]:
    """Fetch opportunities"""
    conn = get_connection()
    cursor = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        query = "SELECT * FROM opportunities WHERE company_id = %s"
        params = [company_id]
        
        if status:
            query += " AND status = %s"
            params.append(status)
        
        query += " ORDER BY created_at DESC LIMIT %s"
        params.append(limit)
        
        cursor.execute(query, params)
        return cursor.fetchall()
    finally:
        cursor.close()
        conn.close()

def fetch_quotes(company_id: str, status: Optional[str] = None, limit: int = 100) -> List[Dict[str, Any]]:
    """Fetch quotes"""
    conn = get_connection()
    cursor = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        query = """
            SELECT q.*, c.customer_name
            FROM quotes q
            LEFT JOIN customers c ON q.customer_id = c.id
            WHERE q.company_id = %s
        """
        params = [company_id]
        
        if status:
            query += " AND q.status = %s"
            params.append(status)
        
        query += " ORDER BY q.quote_date DESC LIMIT %s"
        params.append(limit)
        
        cursor.execute(query, params)
        return cursor.fetchall()
    finally:
        cursor.close()
        conn.close()

def fetch_customers(company_id: str, limit: int = 100) -> List[Dict[str, Any]]:
    """Fetch customers"""
    conn = get_connection()
    cursor = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        cursor.execute("""
            SELECT * FROM customers
            WHERE company_id = %s
            ORDER BY customer_name
            LIMIT %s
        """, (company_id, limit))
        return cursor.fetchall()
    finally:
        cursor.close()
        conn.close()

# ========================================
# ========================================

def fetch_employees(company_id: str, status: Optional[str] = None, limit: int = 100) -> List[Dict[str, Any]]:
    """Fetch employees"""
    conn = get_connection()
    cursor = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        query = "SELECT * FROM employees WHERE company_id = %s"
        params = [company_id]
        
        if status:
            query += " AND status = %s"
            params.append(status)
        
        query += " ORDER BY employee_name LIMIT %s"
        params.append(limit)
        
        cursor.execute(query, params)
        return cursor.fetchall()
    finally:
        cursor.close()
        conn.close()

def fetch_leave_requests(company_id: str, status: Optional[str] = None, limit: int = 100) -> List[Dict[str, Any]]:
    """Fetch leave requests"""
    conn = get_connection()
    cursor = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        query = """
            SELECT lr.*, e.employee_name
            FROM leave_requests lr
            LEFT JOIN employees e ON lr.employee_id = e.id
            WHERE lr.company_id = %s
        """
        params = [company_id]
        
        if status:
            query += " AND lr.status = %s"
            params.append(status)
        
        query += " ORDER BY lr.start_date DESC LIMIT %s"
        params.append(limit)
        
        cursor.execute(query, params)
        return cursor.fetchall()
    finally:
        cursor.close()
        conn.close()

# ========================================
# ========================================

def fetch_stock_on_hand(company_id: str, warehouse_id: Optional[str] = None, limit: int = 100) -> List[Dict[str, Any]]:
    """Fetch stock on hand"""
    conn = get_connection()
    cursor = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        query = """
            SELECT soh.*, p.product_name, p.sku, w.warehouse_name
            FROM stock_on_hand soh
            LEFT JOIN products p ON soh.product_id = p.id
            LEFT JOIN warehouses w ON soh.warehouse_id = w.id
            WHERE soh.company_id = %s
        """
        params = [company_id]
        
        if warehouse_id:
            query += " AND soh.warehouse_id = %s"
            params.append(warehouse_id)
        
        query += " ORDER BY soh.quantity_on_hand ASC LIMIT %s"
        params.append(limit)
        
        cursor.execute(query, params)
        return cursor.fetchall()
    finally:
        cursor.close()
        conn.close()

def fetch_stock_movements(company_id: str, days_back: int = 30, limit: int = 100) -> List[Dict[str, Any]]:
    """Fetch recent stock movements"""
    conn = get_connection()
    cursor = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        cursor.execute("""
            SELECT sm.*, p.product_name, w.warehouse_name
            FROM stock_movements sm
            LEFT JOIN products p ON sm.product_id = p.id
            LEFT JOIN warehouses w ON sm.warehouse_id = w.id
            WHERE sm.company_id = %s
              AND sm.movement_date >= CURRENT_DATE - INTERVAL '%s days'
            ORDER BY sm.movement_date DESC
            LIMIT %s
        """, (company_id, days_back, limit))
        return cursor.fetchall()
    finally:
        cursor.close()
        conn.close()

def fetch_products(company_id: str, limit: int = 100) -> List[Dict[str, Any]]:
    """Fetch products"""
    conn = get_connection()
    cursor = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        cursor.execute("""
            SELECT * FROM products
            WHERE company_id = %s
            ORDER BY product_name
            LIMIT %s
        """, (company_id, limit))
        return cursor.fetchall()
    finally:
        cursor.close()
        conn.close()
