"""Fix model relationships and metadata columns

Revision ID: dc12a8f685ac
Revises: 005_add_analytics_models
Create Date: 2025-10-14 20:00:21.249686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'dc12a8f685ac'
down_revision: Union[str, None] = '005_add_analytics_models'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_versions_simple',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('version_notes', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_number', name='unique_document_version')
    )
    op.create_index(op.f('ix_document_versions_simple_id'), 'document_versions_simple', ['id'], unique=False)
    op.drop_index('idx_document_compliance_document_id', table_name='document_compliance')
    op.drop_table('document_compliance')
    op.drop_table('compliance_metrics')
    op.drop_table('compliance_reports')
    op.drop_table('remittance_invoice_payments')
    op.drop_table('excel_remittance_log')
    op.drop_table('chat_history')
    op.drop_table('data_classifications')
    op.drop_table('invoice_line_items')
    op.drop_table('contract_parties')
    op.drop_table('compliance_frameworks')
    op.drop_table('contract_terms')
    op.drop_table('policy_assessments')
    op.drop_table('pod_items')
    op.drop_table('compliance_assessments')
    op.drop_index('idx_compliance_audit_logs_compliance_relevant', table_name='compliance_audit_logs')
    op.drop_index('idx_compliance_audit_logs_event_type', table_name='compliance_audit_logs')
    op.drop_index('idx_compliance_audit_logs_timestamp', table_name='compliance_audit_logs')
    op.drop_index('idx_compliance_audit_logs_user_id', table_name='compliance_audit_logs')
    op.drop_table('compliance_audit_logs')
    op.drop_index('idx_compliance_violations_severity', table_name='compliance_violations')
    op.drop_index('idx_compliance_violations_status', table_name='compliance_violations')
    op.drop_table('compliance_violations')
    op.drop_index('idx_pod_data_document_id', table_name='pod_data')
    op.drop_index('idx_pod_data_pod_number', table_name='pod_data')
    op.drop_index('idx_pod_data_sap_posted', table_name='pod_data')
    op.drop_table('pod_data')
    op.drop_index('idx_invoice_data_document_id', table_name='invoice_data')
    op.drop_index('idx_invoice_data_invoice_number', table_name='invoice_data')
    op.drop_index('idx_invoice_data_sap_posted', table_name='invoice_data')
    op.drop_table('invoice_data')
    op.drop_index('idx_remittance_data_document_id', table_name='remittance_data')
    op.drop_index('idx_remittance_data_remittance_number', table_name='remittance_data')
    op.drop_index('idx_remittance_data_sap_posted', table_name='remittance_data')
    op.drop_table('remittance_data')
    op.drop_index('idx_sap_integration_log_document_id', table_name='sap_integration_log')
    op.drop_index('idx_sap_integration_log_status', table_name='sap_integration_log')
    op.drop_table('sap_integration_log')
    op.drop_index('idx_contract_data_contract_number', table_name='contract_data')
    op.drop_index('idx_contract_data_document_id', table_name='contract_data')
    op.drop_table('contract_data')
    op.drop_table('compliance_policies')
    op.add_column('account_lockouts', sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False))
    op.add_column('account_lockouts', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False))
    op.alter_column('account_lockouts', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('account_lockouts', 'locked_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('account_lockouts', 'unlock_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('account_lockouts', 'unlocked_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('idx_account_lockouts_user_id', table_name='account_lockouts')
    op.create_index(op.f('ix_account_lockouts_id'), 'account_lockouts', ['id'], unique=False)
    op.alter_column('api_keys', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('api_keys', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text("(datetime('now'))"))
    op.alter_column('api_keys', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text("(datetime('now'))"))
    op.drop_index('idx_api_keys_hash', table_name='api_keys')
    op.drop_index('idx_api_keys_user_id', table_name='api_keys')
    op.add_column('audit_logs', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False))
    op.alter_column('audit_logs', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('LOGIN', 'LOGOUT', 'CREATE', 'READ', 'UPDATE', 'DELETE', 'UPLOAD', 'DOWNLOAD', 'SHARE', 'PERMISSION_CHANGE', 'ROLE_CHANGE', 'SECURITY_EVENT', name='auditaction'),
               existing_nullable=False)
    op.alter_column('audit_logs', 'request_data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'response_data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.alter_column('cloud_storage_connections', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_cloud_storage_connections_id'), 'cloud_storage_connections', ['id'], unique=False)
    op.drop_constraint(None, 'cloud_storage_connections', type_='foreignkey')
    op.create_foreign_key(None, 'cloud_storage_connections', 'integrations', ['integration_id'], ['id'])
    op.add_column('document_branches', sa.Column('branch_metadata', sa.JSON(), nullable=True))
    op.alter_column('document_branches', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index('idx_branch_active', 'document_branches', ['is_active'], unique=False)
    op.create_index('idx_branch_default', 'document_branches', ['is_default'], unique=False)
    op.create_index('idx_document_branch_name', 'document_branches', ['document_id', 'name'], unique=True)
    op.create_index(op.f('ix_document_branches_id'), 'document_branches', ['id'], unique=False)
    op.create_foreign_key(None, 'document_branches', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(None, 'document_branches', 'document_versions', ['source_version_id'], ['id'])
    op.create_foreign_key(None, 'document_branches', 'users', ['created_by'], ['id'])
    op.drop_column('document_branches', 'metadata')
    op.add_column('document_changes', sa.Column('change_metadata', sa.JSON(), nullable=True))
    op.alter_column('document_changes', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index('idx_change_created', 'document_changes', ['created_at'], unique=False)
    op.create_index('idx_change_impact', 'document_changes', ['impact_level'], unique=False)
    op.create_index('idx_change_type', 'document_changes', ['change_type'], unique=False)
    op.create_index('idx_change_version', 'document_changes', ['version_id'], unique=False)
    op.create_index(op.f('ix_document_changes_id'), 'document_changes', ['id'], unique=False)
    op.create_foreign_key(None, 'document_changes', 'document_versions', ['version_id'], ['id'])
    op.create_foreign_key(None, 'document_changes', 'users', ['created_by'], ['id'])
    op.drop_column('document_changes', 'metadata')
    op.add_column('document_versions', sa.Column('branch_name', sa.String(length=100), nullable=False))
    op.add_column('document_versions', sa.Column('parent_version_id', sa.Integer(), nullable=True))
    op.add_column('document_versions', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('document_versions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('document_versions', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('document_versions', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.add_column('document_versions', sa.Column('change_summary', sa.Text(), nullable=True))
    op.add_column('document_versions', sa.Column('change_type', sa.String(length=20), nullable=False))
    op.add_column('document_versions', sa.Column('changes_count', sa.Integer(), nullable=True))
    op.add_column('document_versions', sa.Column('committed_by', sa.Integer(), nullable=True))
    op.add_column('document_versions', sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('document_versions', sa.Column('version_metadata', sa.JSON(), nullable=True))
    op.add_column('document_versions', sa.Column('tags', sa.JSON(), nullable=True))
    op.alter_column('document_versions', 'version_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('document_versions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text("(datetime('now'))"))
    op.alter_column('document_versions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text("(datetime('now'))"))
    op.drop_constraint('unique_document_version', 'document_versions', type_='unique')
    op.create_index('idx_document_branch', 'document_versions', ['document_id', 'branch_name'], unique=False)
    op.create_index('idx_version_created', 'document_versions', ['created_at'], unique=False)
    op.create_index('idx_version_current', 'document_versions', ['is_current'], unique=False)
    op.create_index('idx_version_status', 'document_versions', ['status'], unique=False)
    op.create_foreign_key(None, 'document_versions', 'document_versions', ['parent_version_id'], ['id'])
    op.create_foreign_key(None, 'document_versions', 'users', ['committed_by'], ['id'])
    op.drop_column('document_versions', 'version_notes')
    op.drop_column('document_versions', 'filename')
    op.drop_column('documents', 'indexed_at')
    op.drop_column('documents', 'classification_reasoning')
    op.drop_column('documents', 'document_category')
    op.drop_column('documents', 'processing_status')
    op.drop_column('documents', 'search_keywords')
    op.drop_column('documents', 'processed_at')
    op.drop_column('documents', 'key_topics')
    op.drop_column('documents', 'key_information')
    op.drop_column('documents', 'ocr_confidence')
    op.drop_column('documents', 'content_type')
    op.drop_column('documents', 'entities')
    op.drop_column('documents', 'classification_confidence')
    op.drop_column('documents', 'content_summary')
    op.drop_column('documents', 'extracted_text')
    op.drop_column('documents', 'processing_metadata')
    op.drop_column('documents', 'quality_assessment')
    op.alter_column('email_configurations', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_email_configurations_id'), 'email_configurations', ['id'], unique=False)
    op.drop_constraint(None, 'email_configurations', type_='foreignkey')
    op.create_foreign_key(None, 'email_configurations', 'integrations', ['integration_id'], ['id'])
    op.alter_column('integration_sync_logs', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index('idx_sync_logs_integration_id', table_name='integration_sync_logs')
    op.drop_index('idx_sync_logs_started_at', table_name='integration_sync_logs')
    op.create_index(op.f('ix_integration_sync_logs_id'), 'integration_sync_logs', ['id'], unique=False)
    op.drop_constraint(None, 'integration_sync_logs', type_='foreignkey')
    op.create_foreign_key(None, 'integration_sync_logs', 'integrations', ['integration_id'], ['id'])
    op.alter_column('integrations', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('integrations', 'type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('SAP', 'EMAIL', 'SLACK', 'TEAMS', 'AWS_S3', 'GOOGLE_DRIVE', 'ONEDRIVE', 'WEBHOOK', 'CUSTOM', name='integrationtype'),
               existing_nullable=False)
    op.alter_column('integrations', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', 'PENDING', 'TESTING', name='integrationstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'inactive'"))
    op.alter_column('integrations', 'config',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))
    op.alter_column('integrations', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('idx_integrations_created_by', table_name='integrations')
    op.drop_index('idx_integrations_status', table_name='integrations')
    op.drop_index('idx_integrations_type', table_name='integrations')
    op.create_index(op.f('ix_integrations_id'), 'integrations', ['id'], unique=False)
    op.add_column('login_attempts', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False))
    op.alter_column('login_attempts', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('login_attempts', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index('idx_login_attempts_created_at', table_name='login_attempts')
    op.drop_index('idx_login_attempts_email', table_name='login_attempts')
    op.drop_index('idx_login_attempts_ip', table_name='login_attempts')
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    op.create_index(op.f('ix_login_attempts_id'), 'login_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_login_attempts_ip_address'), 'login_attempts', ['ip_address'], unique=False)
    op.add_column('merge_conflicts', sa.Column('conflict_metadata', sa.JSON(), nullable=True))
    op.alter_column('merge_conflicts', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index('idx_conflict_merge', 'merge_conflicts', ['merge_request_id'], unique=False)
    op.create_index('idx_conflict_resolved', 'merge_conflicts', ['is_resolved'], unique=False)
    op.create_index('idx_conflict_type', 'merge_conflicts', ['conflict_type'], unique=False)
    op.create_index(op.f('ix_merge_conflicts_id'), 'merge_conflicts', ['id'], unique=False)
    op.create_foreign_key(None, 'merge_conflicts', 'merge_requests', ['merge_request_id'], ['id'])
    op.create_foreign_key(None, 'merge_conflicts', 'users', ['resolved_by'], ['id'])
    op.drop_column('merge_conflicts', 'metadata')
    op.add_column('merge_requests', sa.Column('merge_metadata', sa.JSON(), nullable=True))
    op.alter_column('merge_requests', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index('idx_merge_created', 'merge_requests', ['created_at'], unique=False)
    op.create_index('idx_merge_document', 'merge_requests', ['document_id'], unique=False)
    op.create_index('idx_merge_source', 'merge_requests', ['source_version_id'], unique=False)
    op.create_index('idx_merge_status', 'merge_requests', ['status'], unique=False)
    op.create_index('idx_merge_target', 'merge_requests', ['target_version_id'], unique=False)
    op.create_index(op.f('ix_merge_requests_id'), 'merge_requests', ['id'], unique=False)
    op.create_foreign_key(None, 'merge_requests', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(None, 'merge_requests', 'users', ['merged_by'], ['id'])
    op.create_foreign_key(None, 'merge_requests', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'merge_requests', 'users', ['assigned_to'], ['id'])
    op.create_foreign_key(None, 'merge_requests', 'document_versions', ['source_version_id'], ['id'])
    op.create_foreign_key(None, 'merge_requests', 'document_versions', ['target_version_id'], ['id'])
    op.create_foreign_key(None, 'merge_requests', 'document_versions', ['merged_version_id'], ['id'])
    op.drop_column('merge_requests', 'metadata')
    op.add_column('notifications', sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='notificationpriority'), nullable=True))
    op.add_column('notifications', sa.Column('recipient_id', sa.Integer(), nullable=False))
    op.add_column('notifications', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('notifications', sa.Column('task_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('notification_metadata', sa.Text(), nullable=True))
    op.add_column('notifications', sa.Column('action_url', sa.String(length=500), nullable=True))
    op.add_column('notifications', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text("(datetime('now'))"))
    op.alter_column('notifications', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text("(datetime('now'))"))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'users', ['recipient_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'workflow_tasks', ['task_id'], ['id'])
    op.drop_column('notifications', 'push_sent_at')
    op.drop_column('notifications', 'email_sent_at')
    op.drop_column('notifications', 'comment_id')
    op.drop_column('notifications', 'email_sent')
    op.drop_column('notifications', 'push_sent')
    op.drop_column('notifications', 'user_id')
    op.add_column('password_history', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False))
    op.alter_column('password_history', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('password_history', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index('idx_password_history_user_id', table_name='password_history')
    op.create_index(op.f('ix_password_history_id'), 'password_history', ['id'], unique=False)
    op.add_column('permissions', sa.Column('resource_type', sa.String(length=50), nullable=False))
    op.add_column('permissions', sa.Column('permission_type', sa.Enum('READ', 'WRITE', 'DELETE', 'ADMIN', 'EXECUTE', name='permissiontype'), nullable=False))
    op.alter_column('permissions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text("(datetime('now'))"))
    op.alter_column('permissions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text("(datetime('now'))"))
    op.drop_index('idx_permissions_name', table_name='permissions')
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.drop_column('permissions', 'resource')
    op.drop_column('permissions', 'action')
    op.add_column('role_permissions', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('role_permissions', sa.Column('granted_by', sa.Integer(), nullable=True))
    op.add_column('role_permissions', sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('role_permissions', sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False))
    op.add_column('role_permissions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False))
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_foreign_key(None, 'role_permissions', 'users', ['granted_by'], ['id'])
    op.add_column('roles', sa.Column('is_system_role', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('roles', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text("(datetime('now'))"))
    op.alter_column('roles', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text("(datetime('now'))"))
    op.drop_index('idx_roles_name', table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_column('roles', 'is_default')
    op.alter_column('sap_connections', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_sap_connections_id'), 'sap_connections', ['id'], unique=False)
    op.drop_constraint(None, 'sap_connections', type_='foreignkey')
    op.create_foreign_key(None, 'sap_connections', 'integrations', ['integration_id'], ['id'])
    op.add_column('security_events', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False))
    op.alter_column('security_events', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('security_events', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('FAILED_LOGIN', 'SUSPICIOUS_ACTIVITY', 'UNAUTHORIZED_ACCESS', 'PASSWORD_CHANGE', 'ACCOUNT_LOCKED', 'ACCOUNT_UNLOCKED', 'TWO_FACTOR_ENABLED', 'TWO_FACTOR_DISABLED', name='securityeventtype'),
               existing_nullable=False)
    op.alter_column('security_events', 'additional_data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('security_events', 'resolved_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('security_events', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index('idx_security_events_created_at', table_name='security_events')
    op.drop_index('idx_security_events_type', table_name='security_events')
    op.drop_index('idx_security_events_user_id', table_name='security_events')
    op.create_index(op.f('ix_security_events_id'), 'security_events', ['id'], unique=False)
    op.alter_column('security_policies', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('security_policies', 'settings',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('security_policies', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('security_policies', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_security_policies_id'), 'security_policies', ['id'], unique=False)
    op.create_unique_constraint(None, 'security_policies', ['name'])
    op.alter_column('slack_teams_connections', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_slack_teams_connections_id'), 'slack_teams_connections', ['id'], unique=False)
    op.drop_constraint(None, 'slack_teams_connections', type_='foreignkey')
    op.create_foreign_key(None, 'slack_teams_connections', 'integrations', ['integration_id'], ['id'])
    op.add_column('two_factor_auth', sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False))
    op.add_column('two_factor_auth', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False))
    op.alter_column('two_factor_auth', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('two_factor_auth', 'backup_codes',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('two_factor_auth', 'enabled_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('two_factor_auth', 'last_used',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_two_factor_auth_id'), 'two_factor_auth', ['id'], unique=False)
    op.add_column('user_roles', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('user_roles', sa.Column('assigned_by', sa.Integer(), nullable=True))
    op.add_column('user_roles', sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('user_roles', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_roles', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('user_roles', sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False))
    op.add_column('user_roles', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False))
    op.drop_index('idx_user_roles_role_id', table_name='user_roles')
    op.drop_index('idx_user_roles_user_id', table_name='user_roles')
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_foreign_key(None, 'user_roles', 'users', ['assigned_by'], ['id'])
    op.add_column('user_sessions', sa.Column('location', sa.JSON(), nullable=True))
    op.add_column('user_sessions', sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'REVOKED', name='sessionstatus'), nullable=True))
    op.add_column('user_sessions', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_sessions', sa.Column('revoked_by', sa.Integer(), nullable=True))
    op.alter_column('user_sessions', 'refresh_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user_sessions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text("(datetime('now'))"))
    op.drop_index('idx_user_sessions_refresh_token', table_name='user_sessions')
    op.drop_index('idx_user_sessions_token', table_name='user_sessions')
    op.drop_index('idx_user_sessions_user_id', table_name='user_sessions')
    op.create_foreign_key(None, 'user_sessions', 'users', ['revoked_by'], ['id'])
    op.drop_column('user_sessions', 'is_active')
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('avatar_filename', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('github_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('push_notifications', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('date_format', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('time_format', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('ui_preferences', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('privacy_settings', sa.JSON(), nullable=True))
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'is_admin')
    op.alter_column('version_comparisons', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index('idx_comparison_document', 'version_comparisons', ['document_id'], unique=False)
    op.create_index('idx_comparison_expires', 'version_comparisons', ['expires_at'], unique=False)
    op.create_index('idx_comparison_versions', 'version_comparisons', ['version_a_id', 'version_b_id'], unique=True)
    op.create_index(op.f('ix_version_comparisons_id'), 'version_comparisons', ['id'], unique=False)
    op.create_foreign_key(None, 'version_comparisons', 'document_versions', ['version_b_id'], ['id'])
    op.create_foreign_key(None, 'version_comparisons', 'document_versions', ['version_a_id'], ['id'])
    op.create_foreign_key(None, 'version_comparisons', 'documents', ['document_id'], ['id'])
    op.add_column('version_tags', sa.Column('tag_metadata', sa.JSON(), nullable=True))
    op.alter_column('version_tags', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index('idx_tag_document_name', 'version_tags', ['document_id', 'name'], unique=True)
    op.create_index('idx_tag_type', 'version_tags', ['tag_type'], unique=False)
    op.create_index('idx_tag_version', 'version_tags', ['version_id'], unique=False)
    op.create_index(op.f('ix_version_tags_id'), 'version_tags', ['id'], unique=False)
    op.create_foreign_key(None, 'version_tags', 'document_versions', ['version_id'], ['id'])
    op.create_foreign_key(None, 'version_tags', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(None, 'version_tags', 'users', ['created_by'], ['id'])
    op.drop_column('version_tags', 'metadata')
    op.alter_column('webhook_deliveries', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('webhook_deliveries', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('DOCUMENT_CREATED', 'DOCUMENT_UPDATED', 'DOCUMENT_DELETED', 'DOCUMENT_SHARED', 'WORKFLOW_STARTED', 'WORKFLOW_COMPLETED', 'USER_REGISTERED', 'SECURITY_ALERT', 'SYSTEM_ERROR', name='webhookeventtype'),
               existing_nullable=False)
    op.drop_index('idx_webhook_deliveries_triggered_at', table_name='webhook_deliveries')
    op.drop_index('idx_webhook_deliveries_webhook_id', table_name='webhook_deliveries')
    op.create_index(op.f('ix_webhook_deliveries_id'), 'webhook_deliveries', ['id'], unique=False)
    op.drop_constraint(None, 'webhook_deliveries', type_='foreignkey')
    op.create_foreign_key(None, 'webhook_deliveries', 'webhook_endpoints', ['webhook_id'], ['id'])
    op.alter_column('webhook_endpoints', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('webhook_endpoints', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('idx_webhook_endpoints_integration_id', table_name='webhook_endpoints')
    op.create_index(op.f('ix_webhook_endpoints_id'), 'webhook_endpoints', ['id'], unique=False)
    op.drop_constraint(None, 'webhook_endpoints', type_='foreignkey')
    op.create_foreign_key(None, 'webhook_endpoints', 'integrations', ['integration_id'], ['id'])
    op.add_column('workflow_steps', sa.Column('step_number', sa.Integer(), nullable=False))
    op.add_column('workflow_steps', sa.Column('step_data', sa.JSON(), nullable=True))
    op.add_column('workflows', sa.Column('current_step', sa.Integer(), nullable=True))
    op.add_column('workflows', sa.Column('progress_percentage', sa.Integer(), nullable=True))
    op.add_column('workflows', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.add_column('workflows', sa.Column('workflow_data', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'workflows', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.drop_column('workflows', 'workflow_data')
    op.drop_column('workflows', 'assigned_to')
    op.drop_column('workflows', 'progress_percentage')
    op.drop_column('workflows', 'current_step')
    op.drop_column('workflow_steps', 'step_data')
    op.drop_column('workflow_steps', 'step_number')
    op.drop_constraint(None, 'webhook_endpoints', type_='foreignkey')
    op.create_foreign_key(None, 'webhook_endpoints', 'integrations', ['integration_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_webhook_endpoints_id'), table_name='webhook_endpoints')
    op.create_index('idx_webhook_endpoints_integration_id', 'webhook_endpoints', ['integration_id'], unique=False)
    op.alter_column('webhook_endpoints', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('webhook_endpoints', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'webhook_deliveries', type_='foreignkey')
    op.create_foreign_key(None, 'webhook_deliveries', 'webhook_endpoints', ['webhook_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_webhook_deliveries_id'), table_name='webhook_deliveries')
    op.create_index('idx_webhook_deliveries_webhook_id', 'webhook_deliveries', ['webhook_id'], unique=False)
    op.create_index('idx_webhook_deliveries_triggered_at', 'webhook_deliveries', ['triggered_at'], unique=False)
    op.alter_column('webhook_deliveries', 'event_type',
               existing_type=sa.Enum('DOCUMENT_CREATED', 'DOCUMENT_UPDATED', 'DOCUMENT_DELETED', 'DOCUMENT_SHARED', 'WORKFLOW_STARTED', 'WORKFLOW_COMPLETED', 'USER_REGISTERED', 'SECURITY_ALERT', 'SYSTEM_ERROR', name='webhookeventtype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('webhook_deliveries', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('version_tags', sa.Column('metadata', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'version_tags', type_='foreignkey')
    op.drop_constraint(None, 'version_tags', type_='foreignkey')
    op.drop_constraint(None, 'version_tags', type_='foreignkey')
    op.drop_index(op.f('ix_version_tags_id'), table_name='version_tags')
    op.drop_index('idx_tag_version', table_name='version_tags')
    op.drop_index('idx_tag_type', table_name='version_tags')
    op.drop_index('idx_tag_document_name', table_name='version_tags')
    op.alter_column('version_tags', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('version_tags', 'tag_metadata')
    op.drop_constraint(None, 'version_comparisons', type_='foreignkey')
    op.drop_constraint(None, 'version_comparisons', type_='foreignkey')
    op.drop_constraint(None, 'version_comparisons', type_='foreignkey')
    op.drop_index(op.f('ix_version_comparisons_id'), table_name='version_comparisons')
    op.drop_index('idx_comparison_versions', table_name='version_comparisons')
    op.drop_index('idx_comparison_expires', table_name='version_comparisons')
    op.drop_index('idx_comparison_document', table_name='version_comparisons')
    op.alter_column('version_comparisons', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
    op.add_column('users', sa.Column('password_changed_at', sa.TIMESTAMP(), nullable=True))
    op.drop_column('users', 'privacy_settings')
    op.drop_column('users', 'ui_preferences')
    op.drop_column('users', 'time_format')
    op.drop_column('users', 'date_format')
    op.drop_column('users', 'push_notifications')
    op.drop_column('users', 'github_url')
    op.drop_column('users', 'linkedin_url')
    op.drop_column('users', 'website')
    op.drop_column('users', 'location')
    op.drop_column('users', 'avatar_filename')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.add_column('user_sessions', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.create_index('idx_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_index('idx_user_sessions_token', 'user_sessions', ['session_token'], unique=False)
    op.create_index('idx_user_sessions_refresh_token', 'user_sessions', ['refresh_token'], unique=False)
    op.alter_column('user_sessions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text("(datetime('now'))"))
    op.alter_column('user_sessions', 'refresh_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('user_sessions', 'revoked_by')
    op.drop_column('user_sessions', 'revoked_at')
    op.drop_column('user_sessions', 'status')
    op.drop_column('user_sessions', 'location')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.create_index('idx_user_roles_user_id', 'user_roles', ['user_id'], unique=False)
    op.create_index('idx_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    op.drop_column('user_roles', 'updated_at')
    op.drop_column('user_roles', 'created_at')
    op.drop_column('user_roles', 'is_active')
    op.drop_column('user_roles', 'expires_at')
    op.drop_column('user_roles', 'assigned_at')
    op.drop_column('user_roles', 'assigned_by')
    op.drop_column('user_roles', 'id')
    op.drop_index(op.f('ix_two_factor_auth_id'), table_name='two_factor_auth')
    op.alter_column('two_factor_auth', 'last_used',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('two_factor_auth', 'enabled_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('two_factor_auth', 'backup_codes',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('two_factor_auth', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('two_factor_auth', 'updated_at')
    op.drop_column('two_factor_auth', 'created_at')
    op.drop_constraint(None, 'slack_teams_connections', type_='foreignkey')
    op.create_foreign_key(None, 'slack_teams_connections', 'integrations', ['integration_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_slack_teams_connections_id'), table_name='slack_teams_connections')
    op.alter_column('slack_teams_connections', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'security_policies', type_='unique')
    op.drop_index(op.f('ix_security_policies_id'), table_name='security_policies')
    op.alter_column('security_policies', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('security_policies', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('security_policies', 'settings',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('security_policies', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_security_events_id'), table_name='security_events')
    op.create_index('idx_security_events_user_id', 'security_events', ['user_id'], unique=False)
    op.create_index('idx_security_events_type', 'security_events', ['event_type'], unique=False)
    op.create_index('idx_security_events_created_at', 'security_events', ['created_at'], unique=False)
    op.alter_column('security_events', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('security_events', 'resolved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('security_events', 'additional_data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('security_events', 'event_type',
               existing_type=sa.Enum('FAILED_LOGIN', 'SUSPICIOUS_ACTIVITY', 'UNAUTHORIZED_ACCESS', 'PASSWORD_CHANGE', 'ACCOUNT_LOCKED', 'ACCOUNT_UNLOCKED', 'TWO_FACTOR_ENABLED', 'TWO_FACTOR_DISABLED', name='securityeventtype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('security_events', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('security_events', 'updated_at')
    op.drop_constraint(None, 'sap_connections', type_='foreignkey')
    op.create_foreign_key(None, 'sap_connections', 'integrations', ['integration_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_sap_connections_id'), table_name='sap_connections')
    op.alter_column('sap_connections', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('roles', sa.Column('is_default', sa.BOOLEAN(), nullable=True))
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index('idx_roles_name', 'roles', ['name'], unique=False)
    op.alter_column('roles', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text("(datetime('now'))"))
    op.alter_column('roles', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text("(datetime('now'))"))
    op.drop_column('roles', 'is_active')
    op.drop_column('roles', 'is_system_role')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_column('role_permissions', 'updated_at')
    op.drop_column('role_permissions', 'created_at')
    op.drop_column('role_permissions', 'granted_at')
    op.drop_column('role_permissions', 'granted_by')
    op.drop_column('role_permissions', 'id')
    op.add_column('permissions', sa.Column('action', sa.VARCHAR(length=50), nullable=False))
    op.add_column('permissions', sa.Column('resource', sa.VARCHAR(length=50), nullable=False))
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.create_index('idx_permissions_name', 'permissions', ['name'], unique=False)
    op.alter_column('permissions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text("(datetime('now'))"))
    op.alter_column('permissions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text("(datetime('now'))"))
    op.drop_column('permissions', 'permission_type')
    op.drop_column('permissions', 'resource_type')
    op.drop_index(op.f('ix_password_history_id'), table_name='password_history')
    op.create_index('idx_password_history_user_id', 'password_history', ['user_id'], unique=False)
    op.alter_column('password_history', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('password_history', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('password_history', 'updated_at')
    op.add_column('notifications', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.add_column('notifications', sa.Column('push_sent', sa.BOOLEAN(), nullable=True))
    op.add_column('notifications', sa.Column('email_sent', sa.BOOLEAN(), nullable=True))
    op.add_column('notifications', sa.Column('comment_id', sa.INTEGER(), nullable=True))
    op.add_column('notifications', sa.Column('email_sent_at', sa.DATETIME(), nullable=True))
    op.add_column('notifications', sa.Column('push_sent_at', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'comments', ['comment_id'], ['id'])
    op.alter_column('notifications', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text("(datetime('now'))"))
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text("(datetime('now'))"))
    op.drop_column('notifications', 'scheduled_at')
    op.drop_column('notifications', 'action_url')
    op.drop_column('notifications', 'notification_metadata')
    op.drop_column('notifications', 'task_id')
    op.drop_column('notifications', 'is_archived')
    op.drop_column('notifications', 'sender_id')
    op.drop_column('notifications', 'recipient_id')
    op.drop_column('notifications', 'priority')
    op.add_column('merge_requests', sa.Column('metadata', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'merge_requests', type_='foreignkey')
    op.drop_constraint(None, 'merge_requests', type_='foreignkey')
    op.drop_constraint(None, 'merge_requests', type_='foreignkey')
    op.drop_constraint(None, 'merge_requests', type_='foreignkey')
    op.drop_constraint(None, 'merge_requests', type_='foreignkey')
    op.drop_constraint(None, 'merge_requests', type_='foreignkey')
    op.drop_constraint(None, 'merge_requests', type_='foreignkey')
    op.drop_index(op.f('ix_merge_requests_id'), table_name='merge_requests')
    op.drop_index('idx_merge_target', table_name='merge_requests')
    op.drop_index('idx_merge_status', table_name='merge_requests')
    op.drop_index('idx_merge_source', table_name='merge_requests')
    op.drop_index('idx_merge_document', table_name='merge_requests')
    op.drop_index('idx_merge_created', table_name='merge_requests')
    op.alter_column('merge_requests', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('merge_requests', 'merge_metadata')
    op.add_column('merge_conflicts', sa.Column('metadata', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'merge_conflicts', type_='foreignkey')
    op.drop_constraint(None, 'merge_conflicts', type_='foreignkey')
    op.drop_index(op.f('ix_merge_conflicts_id'), table_name='merge_conflicts')
    op.drop_index('idx_conflict_type', table_name='merge_conflicts')
    op.drop_index('idx_conflict_resolved', table_name='merge_conflicts')
    op.drop_index('idx_conflict_merge', table_name='merge_conflicts')
    op.alter_column('merge_conflicts', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('merge_conflicts', 'conflict_metadata')
    op.drop_index(op.f('ix_login_attempts_ip_address'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.create_index('idx_login_attempts_ip', 'login_attempts', ['ip_address'], unique=False)
    op.create_index('idx_login_attempts_email', 'login_attempts', ['email'], unique=False)
    op.create_index('idx_login_attempts_created_at', 'login_attempts', ['created_at'], unique=False)
    op.alter_column('login_attempts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('login_attempts', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('login_attempts', 'updated_at')
    op.drop_index(op.f('ix_integrations_id'), table_name='integrations')
    op.create_index('idx_integrations_type', 'integrations', ['type'], unique=False)
    op.create_index('idx_integrations_status', 'integrations', ['status'], unique=False)
    op.create_index('idx_integrations_created_by', 'integrations', ['created_by'], unique=False)
    op.alter_column('integrations', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('integrations', 'config',
               existing_type=sqlite.JSON(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
    op.alter_column('integrations', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', 'PENDING', 'TESTING', name='integrationstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'inactive'"))
    op.alter_column('integrations', 'type',
               existing_type=sa.Enum('SAP', 'EMAIL', 'SLACK', 'TEAMS', 'AWS_S3', 'GOOGLE_DRIVE', 'ONEDRIVE', 'WEBHOOK', 'CUSTOM', name='integrationtype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('integrations', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'integration_sync_logs', type_='foreignkey')
    op.create_foreign_key(None, 'integration_sync_logs', 'integrations', ['integration_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_integration_sync_logs_id'), table_name='integration_sync_logs')
    op.create_index('idx_sync_logs_started_at', 'integration_sync_logs', ['started_at'], unique=False)
    op.create_index('idx_sync_logs_integration_id', 'integration_sync_logs', ['integration_id'], unique=False)
    op.alter_column('integration_sync_logs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'email_configurations', type_='foreignkey')
    op.create_foreign_key(None, 'email_configurations', 'integrations', ['integration_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_email_configurations_id'), table_name='email_configurations')
    op.alter_column('email_configurations', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('documents', sa.Column('quality_assessment', sa.TEXT(), nullable=True))
    op.add_column('documents', sa.Column('processing_metadata', sa.TEXT(), nullable=True))
    op.add_column('documents', sa.Column('extracted_text', sa.TEXT(), nullable=True))
    op.add_column('documents', sa.Column('content_summary', sa.TEXT(), nullable=True))
    op.add_column('documents', sa.Column('classification_confidence', sa.REAL(), nullable=True))
    op.add_column('documents', sa.Column('entities', sa.TEXT(), nullable=True))
    op.add_column('documents', sa.Column('content_type', sa.TEXT(), nullable=True))
    op.add_column('documents', sa.Column('ocr_confidence', sa.REAL(), nullable=True))
    op.add_column('documents', sa.Column('key_information', sa.TEXT(), nullable=True))
    op.add_column('documents', sa.Column('key_topics', sa.TEXT(), nullable=True))
    op.add_column('documents', sa.Column('processed_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('documents', sa.Column('search_keywords', sa.TEXT(), nullable=True))
    op.add_column('documents', sa.Column('processing_status', sa.TEXT(), server_default=sa.text("'pending'"), nullable=True))
    op.add_column('documents', sa.Column('document_category', sa.TEXT(), nullable=True))
    op.add_column('documents', sa.Column('classification_reasoning', sa.TEXT(), nullable=True))
    op.add_column('documents', sa.Column('indexed_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('document_versions', sa.Column('filename', sa.VARCHAR(length=255), nullable=False))
    op.add_column('document_versions', sa.Column('version_notes', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'document_versions', type_='foreignkey')
    op.drop_constraint(None, 'document_versions', type_='foreignkey')
    op.drop_index('idx_version_status', table_name='document_versions')
    op.drop_index('idx_version_current', table_name='document_versions')
    op.drop_index('idx_version_created', table_name='document_versions')
    op.drop_index('idx_document_branch', table_name='document_versions')
    op.create_unique_constraint('unique_document_version', 'document_versions', ['document_id', 'version_number'])
    op.alter_column('document_versions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text("(datetime('now'))"))
    op.alter_column('document_versions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text("(datetime('now'))"))
    op.alter_column('document_versions', 'version_number',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('document_versions', 'tags')
    op.drop_column('document_versions', 'version_metadata')
    op.drop_column('document_versions', 'committed_at')
    op.drop_column('document_versions', 'committed_by')
    op.drop_column('document_versions', 'changes_count')
    op.drop_column('document_versions', 'change_type')
    op.drop_column('document_versions', 'change_summary')
    op.drop_column('document_versions', 'is_published')
    op.drop_column('document_versions', 'status')
    op.drop_column('document_versions', 'description')
    op.drop_column('document_versions', 'title')
    op.drop_column('document_versions', 'parent_version_id')
    op.drop_column('document_versions', 'branch_name')
    op.add_column('document_changes', sa.Column('metadata', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'document_changes', type_='foreignkey')
    op.drop_constraint(None, 'document_changes', type_='foreignkey')
    op.drop_index(op.f('ix_document_changes_id'), table_name='document_changes')
    op.drop_index('idx_change_version', table_name='document_changes')
    op.drop_index('idx_change_type', table_name='document_changes')
    op.drop_index('idx_change_impact', table_name='document_changes')
    op.drop_index('idx_change_created', table_name='document_changes')
    op.alter_column('document_changes', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('document_changes', 'change_metadata')
    op.add_column('document_branches', sa.Column('metadata', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'document_branches', type_='foreignkey')
    op.drop_constraint(None, 'document_branches', type_='foreignkey')
    op.drop_constraint(None, 'document_branches', type_='foreignkey')
    op.drop_index(op.f('ix_document_branches_id'), table_name='document_branches')
    op.drop_index('idx_document_branch_name', table_name='document_branches')
    op.drop_index('idx_branch_default', table_name='document_branches')
    op.drop_index('idx_branch_active', table_name='document_branches')
    op.alter_column('document_branches', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('document_branches', 'branch_metadata')
    op.drop_constraint(None, 'cloud_storage_connections', type_='foreignkey')
    op.create_foreign_key(None, 'cloud_storage_connections', 'integrations', ['integration_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_cloud_storage_connections_id'), table_name='cloud_storage_connections')
    op.alter_column('cloud_storage_connections', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('audit_logs', 'response_data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'request_data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.Enum('LOGIN', 'LOGOUT', 'CREATE', 'READ', 'UPDATE', 'DELETE', 'UPLOAD', 'DOWNLOAD', 'SHARE', 'PERMISSION_CHANGE', 'ROLE_CHANGE', 'SECURITY_EVENT', name='auditaction'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('audit_logs', 'updated_at')
    op.create_index('idx_api_keys_user_id', 'api_keys', ['user_id'], unique=False)
    op.create_index('idx_api_keys_hash', 'api_keys', ['key_hash'], unique=False)
    op.alter_column('api_keys', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text("(datetime('now'))"))
    op.alter_column('api_keys', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text("(datetime('now'))"))
    op.alter_column('api_keys', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_account_lockouts_id'), table_name='account_lockouts')
    op.create_index('idx_account_lockouts_user_id', 'account_lockouts', ['user_id'], unique=False)
    op.alter_column('account_lockouts', 'unlocked_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('account_lockouts', 'unlock_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('account_lockouts', 'locked_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('account_lockouts', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('account_lockouts', 'updated_at')
    op.drop_column('account_lockouts', 'created_at')
    op.create_table('compliance_policies',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('framework_id', sa.INTEGER(), nullable=False),
    sa.Column('policy_id', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('category', sa.TEXT(), nullable=True),
    sa.Column('implementation_guide', sa.TEXT(), nullable=True),
    sa.Column('technical_controls', sa.TEXT(), nullable=True),
    sa.Column('procedural_controls', sa.TEXT(), nullable=True),
    sa.Column('risk_level', sa.TEXT(), server_default=sa.text("'medium'"), nullable=True),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('5'), nullable=True),
    sa.Column('is_mandatory', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('is_implemented', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('implementation_date', sa.DATETIME(), nullable=True),
    sa.Column('next_review_date', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.CheckConstraint("risk_level IN ('low', 'medium', 'high', 'critical')"),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.Column('contract_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('contract_date', sa.DATE(), nullable=True),
    sa.Column('effective_date', sa.DATE(), nullable=True),
    sa.Column('expiration_date', sa.DATE(), nullable=True),
    sa.Column('contract_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'USD'"), nullable=True),
    sa.Column('payment_terms', sa.TEXT(), nullable=True),
    sa.Column('renewal_terms', sa.TEXT(), nullable=True),
    sa.Column('termination_clause', sa.TEXT(), nullable=True),
    sa.Column('sap_posted', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.Column('sap_document_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('sap_posting_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('sap_error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contract_data_document_id', 'contract_data', ['document_id'], unique=False)
    op.create_index('idx_contract_data_contract_number', 'contract_data', ['contract_number'], unique=False)
    op.create_table('sap_integration_log',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('business_data_id', sa.INTEGER(), nullable=True),
    sa.Column('sap_transaction_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('sap_document_type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('sap_company_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('integration_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('sap_document_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('sap_response', sa.TEXT(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('initiated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('next_retry_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sap_integration_log_status', 'sap_integration_log', ['integration_status'], unique=False)
    op.create_index('idx_sap_integration_log_document_id', 'sap_integration_log', ['document_id'], unique=False)
    op.create_table('remittance_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.Column('remittance_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('payment_date', sa.DATE(), nullable=True),
    sa.Column('payer_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('payer_account_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('payer_reference', sa.VARCHAR(length=100), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=100), nullable=True),
    sa.Column('total_payment_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'USD'"), nullable=True),
    sa.Column('bank_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('bank_account_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('bank_routing_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('bank_reference_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('sap_posted', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.Column('sap_document_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('sap_posting_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('sap_error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_remittance_data_sap_posted', 'remittance_data', ['sap_posted'], unique=False)
    op.create_index('idx_remittance_data_remittance_number', 'remittance_data', ['remittance_number'], unique=False)
    op.create_index('idx_remittance_data_document_id', 'remittance_data', ['document_id'], unique=False)
    op.create_table('invoice_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('invoice_date', sa.DATE(), nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('po_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('vendor_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('vendor_address', sa.TEXT(), nullable=True),
    sa.Column('vendor_phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('vendor_email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('vendor_tax_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('customer_address', sa.TEXT(), nullable=True),
    sa.Column('customer_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('tax_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'USD'"), nullable=True),
    sa.Column('payment_terms', sa.VARCHAR(length=255), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=100), nullable=True),
    sa.Column('sap_posted', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.Column('sap_document_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('sap_posting_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('sap_error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_invoice_data_sap_posted', 'invoice_data', ['sap_posted'], unique=False)
    op.create_index('idx_invoice_data_invoice_number', 'invoice_data', ['invoice_number'], unique=False)
    op.create_index('idx_invoice_data_document_id', 'invoice_data', ['document_id'], unique=False)
    op.create_table('pod_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.Column('pod_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('delivery_date', sa.DATE(), nullable=True),
    sa.Column('delivery_time', sa.TIME(), nullable=True),
    sa.Column('tracking_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('carrier_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('driver_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('vehicle_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('shipper_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('shipper_address', sa.TEXT(), nullable=True),
    sa.Column('recipient_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('recipient_address', sa.TEXT(), nullable=True),
    sa.Column('contact_person', sa.VARCHAR(length=255), nullable=True),
    sa.Column('signature_captured', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.Column('delivery_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('special_instructions', sa.TEXT(), nullable=True),
    sa.Column('damages_noted', sa.TEXT(), nullable=True),
    sa.Column('sap_posted', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.Column('sap_document_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('sap_posting_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('sap_error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pod_data_sap_posted', 'pod_data', ['sap_posted'], unique=False)
    op.create_index('idx_pod_data_pod_number', 'pod_data', ['pod_number'], unique=False)
    op.create_index('idx_pod_data_document_id', 'pod_data', ['document_id'], unique=False)
    op.create_table('compliance_violations',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('framework_id', sa.INTEGER(), nullable=False),
    sa.Column('policy_id', sa.INTEGER(), nullable=True),
    sa.Column('violation_type', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('severity', sa.TEXT(), nullable=False),
    sa.Column('impact_description', sa.TEXT(), nullable=True),
    sa.Column('affected_systems', sa.TEXT(), nullable=True),
    sa.Column('affected_data_types', sa.TEXT(), nullable=True),
    sa.Column('detected_at', sa.DATETIME(), nullable=False),
    sa.Column('detected_by', sa.TEXT(), nullable=True),
    sa.Column('detection_method', sa.TEXT(), server_default=sa.text("'manual'"), nullable=True),
    sa.Column('related_audit_logs', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'open'"), nullable=True),
    sa.Column('assigned_to', sa.INTEGER(), nullable=True),
    sa.Column('response_plan', sa.TEXT(), nullable=True),
    sa.Column('remediation_steps', sa.TEXT(), nullable=True),
    sa.Column('response_due_date', sa.DATETIME(), nullable=True),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.Column('closed_at', sa.DATETIME(), nullable=True),
    sa.Column('reported_to_authorities', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('authority_reference', sa.TEXT(), nullable=True),
    sa.Column('external_notifications', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')"),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['compliance_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_compliance_violations_status', 'compliance_violations', ['status'], unique=False)
    op.create_index('idx_compliance_violations_severity', 'compliance_violations', ['severity'], unique=False)
    op.create_table('compliance_audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('event_type', sa.TEXT(), nullable=False),
    sa.Column('event_category', sa.TEXT(), nullable=True),
    sa.Column('event_description', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.TEXT(), nullable=True),
    sa.Column('session_id', sa.TEXT(), nullable=True),
    sa.Column('ip_address', sa.TEXT(), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('request_method', sa.TEXT(), nullable=True),
    sa.Column('request_url', sa.TEXT(), nullable=True),
    sa.Column('request_headers', sa.TEXT(), nullable=True),
    sa.Column('request_body', sa.TEXT(), nullable=True),
    sa.Column('response_status', sa.INTEGER(), nullable=True),
    sa.Column('response_time_ms', sa.REAL(), nullable=True),
    sa.Column('resource_type', sa.TEXT(), nullable=True),
    sa.Column('resource_id', sa.TEXT(), nullable=True),
    sa.Column('resource_name', sa.TEXT(), nullable=True),
    sa.Column('old_values', sa.TEXT(), nullable=True),
    sa.Column('new_values', sa.TEXT(), nullable=True),
    sa.Column('risk_level', sa.TEXT(), server_default=sa.text("'low'"), nullable=True),
    sa.Column('compliance_relevant', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('retention_until', sa.DATETIME(), nullable=True),
    sa.Column('country', sa.TEXT(), nullable=True),
    sa.Column('region', sa.TEXT(), nullable=True),
    sa.Column('city', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("event_type IN ('user_login', 'user_logout', 'document_access', 'document_upload', 'document_download', 'document_delete', 'document_share', 'permission_change', 'system_config', 'data_export', 'backup_created', 'backup_restored', 'security_incident', 'compliance_violation')"),
    sa.CheckConstraint("risk_level IN ('low', 'medium', 'high', 'critical')"),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_compliance_audit_logs_user_id', 'compliance_audit_logs', ['user_id'], unique=False)
    op.create_index('idx_compliance_audit_logs_timestamp', 'compliance_audit_logs', ['timestamp'], unique=False)
    op.create_index('idx_compliance_audit_logs_event_type', 'compliance_audit_logs', ['event_type'], unique=False)
    op.create_index('idx_compliance_audit_logs_compliance_relevant', 'compliance_audit_logs', ['compliance_relevant'], unique=False)
    op.create_table('compliance_assessments',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('framework_id', sa.INTEGER(), nullable=False),
    sa.Column('assessment_name', sa.TEXT(), nullable=False),
    sa.Column('assessment_type', sa.TEXT(), server_default=sa.text("'internal'"), nullable=True),
    sa.Column('scope', sa.TEXT(), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending_review'"), nullable=True),
    sa.Column('overall_score', sa.REAL(), nullable=True),
    sa.Column('findings_summary', sa.TEXT(), nullable=True),
    sa.Column('recommendations', sa.TEXT(), nullable=True),
    sa.Column('assessor_name', sa.TEXT(), nullable=True),
    sa.Column('assessor_organization', sa.TEXT(), nullable=True),
    sa.Column('assessor_credentials', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.CheckConstraint("status IN ('compliant', 'non_compliant', 'pending_review', 'remediation_required')"),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pod_items',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('pod_data_id', sa.INTEGER(), nullable=False),
    sa.Column('item_number', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('quantity_shipped', sa.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('quantity_delivered', sa.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=50), nullable=True),
    sa.Column('condition_notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['pod_data_id'], ['pod_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_assessments',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('assessment_id', sa.INTEGER(), nullable=False),
    sa.Column('policy_id', sa.INTEGER(), nullable=False),
    sa.Column('compliance_status', sa.TEXT(), nullable=False),
    sa.Column('compliance_score', sa.REAL(), nullable=True),
    sa.Column('findings', sa.TEXT(), nullable=True),
    sa.Column('evidence', sa.TEXT(), nullable=True),
    sa.Column('gaps_identified', sa.TEXT(), nullable=True),
    sa.Column('remediation_required', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('remediation_plan', sa.TEXT(), nullable=True),
    sa.Column('remediation_due_date', sa.DATETIME(), nullable=True),
    sa.Column('remediation_owner', sa.INTEGER(), nullable=True),
    sa.Column('risk_level', sa.TEXT(), server_default=sa.text("'medium'"), nullable=True),
    sa.Column('risk_description', sa.TEXT(), nullable=True),
    sa.Column('assessed_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.CheckConstraint("compliance_status IN ('compliant', 'non_compliant', 'pending_review', 'remediation_required')"),
    sa.CheckConstraint("risk_level IN ('low', 'medium', 'high', 'critical')"),
    sa.ForeignKeyConstraint(['assessment_id'], ['compliance_assessments.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['compliance_policies.id'], ),
    sa.ForeignKeyConstraint(['remediation_owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_terms',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('contract_data_id', sa.INTEGER(), nullable=False),
    sa.Column('term_description', sa.TEXT(), nullable=True),
    sa.Column('term_category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['contract_data_id'], ['contract_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_frameworks',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('framework', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('version', sa.TEXT(), server_default=sa.text("'1.0'"), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('retention_period_days', sa.INTEGER(), server_default=sa.text('(2555)'), nullable=True),
    sa.Column('audit_frequency_days', sa.INTEGER(), server_default=sa.text('(90)'), nullable=True),
    sa.Column('risk_assessment_frequency_days', sa.INTEGER(), server_default=sa.text('(365)'), nullable=True),
    sa.Column('notification_enabled', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('alert_threshold_hours', sa.INTEGER(), server_default=sa.text('(24)'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.CheckConstraint("framework IN ('gdpr', 'hipaa', 'sox', 'iso27001', 'pci_dss', 'ccpa', 'ferpa', 'custom')"),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework')
    )
    op.create_table('contract_parties',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('contract_data_id', sa.INTEGER(), nullable=False),
    sa.Column('party_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('party_role', sa.VARCHAR(length=100), nullable=True),
    sa.Column('party_address', sa.TEXT(), nullable=True),
    sa.Column('contact_person', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['contract_data_id'], ['contract_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_line_items',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('invoice_data_id', sa.INTEGER(), nullable=False),
    sa.Column('line_number', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('unit_price', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('tax_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('gl_account', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cost_center', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_data_id'], ['invoice_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_classifications',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('classification_name', sa.TEXT(), nullable=False),
    sa.Column('classification_level', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('access_requirements', sa.TEXT(), nullable=True),
    sa.Column('storage_requirements', sa.TEXT(), nullable=True),
    sa.Column('transmission_requirements', sa.TEXT(), nullable=True),
    sa.Column('retention_requirements', sa.TEXT(), nullable=True),
    sa.Column('disposal_requirements', sa.TEXT(), nullable=True),
    sa.Column('applicable_frameworks', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('classification_level BETWEEN 1 AND 5'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classification_name')
    )
    op.create_table('chat_history',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('response', sa.TEXT(), nullable=False),
    sa.Column('document_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('excel_remittance_log',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('total_records', sa.INTEGER(), nullable=True),
    sa.Column('processed_records', sa.INTEGER(), nullable=True),
    sa.Column('failed_records', sa.INTEGER(), nullable=True),
    sa.Column('processing_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('error_details', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remittance_invoice_payments',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('remittance_data_id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('invoice_date', sa.DATE(), nullable=True),
    sa.Column('original_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('payment_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('discount_taken', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('balance_remaining', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['remittance_data_id'], ['remittance_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_reports',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('framework_id', sa.INTEGER(), nullable=True),
    sa.Column('report_name', sa.TEXT(), nullable=False),
    sa.Column('report_type', sa.TEXT(), server_default=sa.text("'periodic'"), nullable=True),
    sa.Column('report_period_start', sa.DATETIME(), nullable=True),
    sa.Column('report_period_end', sa.DATETIME(), nullable=True),
    sa.Column('executive_summary', sa.TEXT(), nullable=True),
    sa.Column('findings', sa.TEXT(), nullable=True),
    sa.Column('metrics', sa.TEXT(), nullable=True),
    sa.Column('recommendations', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'draft'"), nullable=True),
    sa.Column('approved_by', sa.INTEGER(), nullable=True),
    sa.Column('approved_at', sa.DATETIME(), nullable=True),
    sa.Column('recipients', sa.TEXT(), nullable=True),
    sa.Column('published_at', sa.DATETIME(), nullable=True),
    sa.Column('file_path', sa.TEXT(), nullable=True),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('file_hash', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_metrics',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('framework_id', sa.INTEGER(), nullable=True),
    sa.Column('metric_name', sa.TEXT(), nullable=False),
    sa.Column('metric_type', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('current_value', sa.REAL(), nullable=True),
    sa.Column('target_value', sa.REAL(), nullable=True),
    sa.Column('threshold_warning', sa.REAL(), nullable=True),
    sa.Column('threshold_critical', sa.REAL(), nullable=True),
    sa.Column('calculation_method', sa.TEXT(), nullable=True),
    sa.Column('data_sources', sa.TEXT(), nullable=True),
    sa.Column('update_frequency', sa.TEXT(), nullable=True),
    sa.Column('last_calculated', sa.DATETIME(), nullable=True),
    sa.Column('next_calculation', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_compliance',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.Column('classification_id', sa.INTEGER(), nullable=True),
    sa.Column('compliance_status', sa.TEXT(), server_default=sa.text("'pending_review'"), nullable=True),
    sa.Column('last_reviewed', sa.DATETIME(), nullable=True),
    sa.Column('next_review_due', sa.DATETIME(), nullable=True),
    sa.Column('contains_personal_data', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('data_subjects', sa.TEXT(), nullable=True),
    sa.Column('processing_purposes', sa.TEXT(), nullable=True),
    sa.Column('legal_basis', sa.TEXT(), nullable=True),
    sa.Column('retention_period_years', sa.INTEGER(), nullable=True),
    sa.Column('disposal_date', sa.DATETIME(), nullable=True),
    sa.Column('disposal_method', sa.TEXT(), nullable=True),
    sa.Column('access_log_retention_days', sa.INTEGER(), server_default=sa.text('(2555)'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.CheckConstraint("compliance_status IN ('compliant', 'non_compliant', 'pending_review', 'remediation_required')"),
    sa.ForeignKeyConstraint(['classification_id'], ['data_classifications.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_compliance_document_id', 'document_compliance', ['document_id'], unique=False)
    op.drop_index(op.f('ix_document_versions_simple_id'), table_name='document_versions_simple')
    op.drop_table('document_versions_simple')
    # ### end Alembic commands ###
